POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "A very interesting blog title",
    "author": "John Doe",
    "url": "https://example.com/blog",
    "likes": 0
}

### post blog with user token
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRva2VuYm95IiwiaWQiOiI2M2UxMjIwY2M5YWRjN2IyMGZhMzlmYzkiLCJpYXQiOjE2NzU2OTg3MTN9.hKOGWb3NKbAFJE67YDq2mtLGstgS5F7RQnColwXiR-M

{
    "title": "A blog about token authorization",
    "author": "A. Bearer",
    "url": "https://example.com/blog",
    "likes": 99
}


### send body without author field

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Blog without author",
    "url": "https://example.com/blog",
    "likes": 0
}

### send body without url field

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "A very interesting blog title",
    "author": "John Doe",
    "likes": 0
}

### send body without title field

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "John Doe",
    "url": "https://example.com/blog",
    "likes": 0
}