POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "A very interesting blog title",
    "author": "John Doe",
    "url": "https://example.com/blog",
    "likes": 0
}

### post blog with user token
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRva2VuYm95IiwiaWQiOiI2M2UyMzYzODM5ZTExZWQ4M2U5ODY1NzUiLCJpYXQiOjE2NzU3Njk0MDZ9.WiMwd1Qy5KvMA9n6yiDS6XCp7DNNmQd-rBMG6FAJABI

{
    "title": "A blog about token authorization",
    "author": "A. Bearer",
    "url": "https://example.com/blog",
    "likes": 99
}

### post blog without user token
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "A blog post without authorization/token",
    "author": "Not A. Token",
    "url": "https://example.com/blog",
    "likes": 0
}


### send body without author field

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Blog without author",
    "url": "https://example.com/blog",
    "likes": 0
}

### send body without url field

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "A very interesting blog title",
    "author": "John Doe",
    "likes": 0
}

### send body without title field

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "John Doe",
    "url": "https://example.com/blog",
    "likes": 0
}