GET https://phonebook-backend-38ih.onrender.com/api/persons

###

GET https://phonebook-backend-38ih.onrender.com/info

###
GET https://phonebook-backend-38ih.onrender.com/api/persons/1

###
GET https://phonebook-backend-38ih.onrender.com/api/persons/8

###
POST https://phonebook-backend-38ih.onrender.com/api/persons
Content-Type: application/json

{
    "name": "New Name",
    "number": "123-456"
}

### 
POST https://phonebook-backend-38ih.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Another New Name",
    "number": "123-456-987"
}

### no content
POST https://phonebook-backend-38ih.onrender.com/api/persons
Content-Type: application/json

### name missing
POST https://phonebook-backend-38ih.onrender.com/api/persons
Content-Type: application/json

{
    "number": "123-456-987"
}

### number missing
POST https://phonebook-backend-38ih.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Another New Name"
}

###
DELETE https://phonebook-backend-38ih.onrender.com/api/persons/1

###
DELETE https://phonebook-backend-38ih.onrender.com/api/persons/8