GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/63cd8f992048e1df7322714c

###
GET http://localhost:3001/api/persons/8

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "New Name",
    "number": "123-456"
}

### 
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Another New Name",
    "number": "123-456-987"
}

### 
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jane Doe",
    "number": "00-11-22-33"
}

### no content
POST http://localhost:3001/api/persons
Content-Type: application/json

### name missing
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "123-456-987"
}

### number missing
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Another New Name"
}

###
DELETE http://localhost:3001/api/persons/63cd8f603540050b9990d359

###
DELETE http://localhost:3001/api/persons/8